/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIdImport } from './routes/profile/$id'
import { Route as EventDetailsIdImport } from './routes/event-details/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdRoute = ProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRoute,
} as any)

const EventDetailsIdRoute = EventDetailsIdImport.update({
  id: '/event-details/$id',
  path: '/event-details/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/event-details/$id': {
      id: '/event-details/$id'
      path: '/event-details/$id'
      fullPath: '/event-details/$id'
      preLoaderRoute: typeof EventDetailsIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event-details/$id': typeof EventDetailsIdRoute
  '/profile/$id': typeof ProfileIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event-details/$id': typeof EventDetailsIdRoute
  '/profile/$id': typeof ProfileIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/event-details/$id': typeof EventDetailsIdRoute
  '/profile/$id': typeof ProfileIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/event-details/$id' | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/event-details/$id' | '/profile/$id'
  id: '__root__' | '/' | '/event-details/$id' | '/profile/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventDetailsIdRoute: typeof EventDetailsIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventDetailsIdRoute: EventDetailsIdRoute,
  ProfileIdRoute: ProfileIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/event-details/$id",
        "/profile/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/event-details/$id": {
      "filePath": "event-details/$id.tsx"
    },
    "/profile/$id": {
      "filePath": "profile/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
